#+title: man kati
#+begin_export html
<div class="about">
   <div class="about-column">KATI(6)</div>
   <div class="about-column">Games Manual</div>
   <div class="about-column">KATI(6)</div>
</div>
#+end_export
*NAME*
       #+attr_html: :class about-indented
       #+BEGIN_DIV
       kati - just kati...
            (I use Arch btw.)
       #+END_DIV    

*SYNOPSIS*
       #+attr_html: :class about-indented
       *kati* [OPTION]... [FILE]...
       

*DESCRIPTION*
       #+attr_html: :class about-indented
       #+BEGIN_DIV
       *kati* is a teminal tool/game from the 90s available for Linux
       or BSD platforms, preferably Arch, Gentoo or OpenBSD.
       *kati* works best with Emacs, other editors cause unpredictable and
       most likely undesired behaviour.
       Although *kati* is device-independent best results are achieved on
       Thinkpads.
       *kati* can also be used outdoor, mainly to explore abandoned buildings
      	      #+END_DIV
       *-asm*
              #+attr_html: :class about-indented-deep
	      #+BEGIN_DIV
              read or write x86, 8051 or arm Assembly code.
	      #+END_DIV
       *-b*, *--bash*
              #+attr_html: :class about-indented-deep
	      #+BEGIN_DIV	      
              read or write Bash scripts
	      #+END_DIV
       *-c*, *--club-mate*
              #+attr_html: :class about-indented-deep
	      #+BEGIN_DIV	      
              activates Club Mate mode: every task gets executed 3 times faster
	      when *kati* gets at least 1 bottle of Club Mate as input
	      (execution time can be further improved with the *pizza* or
              *chocolate* hack.
	                #+END_DIV
       *-C/C++*
              #+attr_html: :class about-indented-deep
	      #+BEGIN_DIV	      
              read or write C/C++ code
       #+END_DIV
       *-CSS/HTML-*
              #+attr_html: :class about-indented-deep
	      #+BEGIN_DIV	      
              use this option *only in emergencies*
	      *kati* is not suitable for web development
	      you'll get results but most likely not the ones you expected
       #+END_DIV
       *-DnD*
              #+attr_html: :class about-indented-deep
	      #+BEGIN_DIV	      
              activate Dungeons & Dragons mode: an advanced AI generates exciting
	      and absurd (and unnecessarily brutal) campagnes for a Massive Multiplayer
	      Tabletop Roleplay Game
	         #+END_DIV
       *-h*, *--haskell*       
              #+attr_html: :class about-indented-deep
	      #+BEGIN_DIV	      
              read or write Haskell code
	      side effects: can result in lectures about why everyone should use
	      xmonad as WM
       #+END_DIV
       *-l*, *--lisp*
              #+attr_html: :class about-indented-deep
	      #+BEGIN_DIV	      
              read or write Lisp code
	      warning: can cause overheating and unpredictable overreactions
             #+END_DIV
       *-p*, *--python*
              #+attr_html: :class about-indented-deep
	      #+BEGIN_DIV	      
              read or write Python code
       #+END_DIV
       *-3d*
              #+attr_html: :class about-indented-deep
	      #+BEGIN_DIV	      
              activate 3D-printing capability
             #+END_DIV
       #+attr_html: :class about-indented
       #+BEGIN_DIV       
      (Note: execution of code with *kati* is still buggy.
	     In some cases it doesn't work at all, in other cases *kati*
             just takes forever to finish execution)
       #+END_DIV
*BUGS*
       #+attr_html: :class about-indented
       #+BEGIN_DIV       
       plenty
       #+END_DIV
*AUTHORS*
       #+attr_html: :class about-indented
       #+BEGIN_DIV       
       kati's parents
       #+END_DIV
*COPYRIGHT*
       #+attr_html: :class about-indented
       #+BEGIN_DIV       
       changes and redistribution of *kati* are prohibited by law
       #+END_DIV


#+begin_export html
<div class="about">
   <div class="about-column">KATI(6)</div>
   <div class="about-column">Games Manual</div>
   <div class="about-column">KATI(6)</div>
</div>
#+end_export
