#+title: man kati
#+begin_export html
<div class="about">
   <div class="about-column">KATI(6)</div>
   <div class="about-column">Games Manual</div>
   <div class="about-column">KATI(6)</div>
</div>
#+end_export
*NAME*
       #+attr_html: :class about-indented
       #+BEGIN_DIV
       kati - terminal gremlin, hardware tinkerer, occasional dungeon master.
            (I use Arch btw.)
       #+END_DIV    

*SYNOPSIS*
       #+attr_html: :class about-indented
       *kati* [OPTION]... [FILE]...
       

*DESCRIPTION*
       #+attr_html: :class about-indented
       #+BEGIN_DIV
       *kati* is a terminal tool/game from the early 90s that still appears to run
       on modern Linux systems, although the maintainers deny responsibility.

       Typical behaviour includes writing low-level code for a living, designing strange
       little electronic devices, and occasionally turning a perfectly normal
       idea into a PCB.

       *kati* works best with Emacs. Other editors may appear functional at
       first, but results cannot be guaranteed.

       Although *kati* is device-independent, best results are achieved on
       ThinkPads and other keyboards capable of surviving both debugging
       sessions and midnight project ideas.

       *kati* can also be used outdoors, mostly for exploring abandoned
       buildings, collecting questionable artifacts, and bringing home
       objects that later turn into props or electronics projects.
	      #+END_DIV
       *-asm*
              #+attr_html: :class about-indented-deep
	      #+BEGIN_DIV
              read or write Assembly code (x86, 8051, ARM… and whatever else
              the situation unexpectedly requires).
	      #+END_DIV
       *-b*, *--bash*
              #+attr_html: :class about-indented-deep
	      #+BEGIN_DIV	      
              read or write Bash scripts, mostly to automate things that
              absolutely should not be done manually more than once.
	      #+END_DIV
       *-c*, *--club-mate*
              #+attr_html: :class about-indented-deep
	      #+BEGIN_DIV	      
              activates Club Mate mode: every task gets executed 3 times
	      faster when *kati* gets at least 1 bottle of Club Mate as input
	      (execution time can be further improved with the *pizza* or
              *chocolate* hack.
	                #+END_DIV
       *-C/C++*
              #+attr_html: :class about-indented-deep
	      #+BEGIN_DIV	      
              read or write C/C++ code, usually in places where mistakes are
              exciting and success is suspiciously quiet.
       #+END_DIV
       *-CSS/HTML-*
              #+attr_html: :class about-indented-deep
	      #+BEGIN_DIV	      
              use this option *only in emergencies*
	      *kati* is not suitable for web development
	      you'll get results but most likely not the ones you expected
       #+END_DIV
       *-DnD*
              #+attr_html: :class about-indented-deep
	      #+BEGIN_DIV	      
              activate Dungeons & Dragons mode: DM functionality enabled.
	      Generates campaigns with excessive lore, suspiciously detailed
	      handouts, and players who will ignore every hint until the
	      dramatic reveal.
	         #+END_DIV
       *-h*, *--haskell*       
              #+attr_html: :class about-indented-deep
	      #+BEGIN_DIV	      
              read or write Haskell code
	      side effects: can result in lectures about why everyone should
	      use xmonad as WM
       #+END_DIV
       *-l*, *--lisp*
              #+attr_html: :class about-indented-deep
	      #+BEGIN_DIV	      
              read or write Lisp code
	      warning: can cause overheating and unpredictable overreactions
             #+END_DIV
       *-p*, *--python*
              #+attr_html: :class about-indented-deep
	      #+BEGIN_DIV	      
              read or write Python code, usually to glue together things that
              were never meant to work together.
       #+END_DIV
       *-3d*
              #+attr_html: :class about-indented-deep
	      #+BEGIN_DIV	      
              activate 3D-printing capability (frequently followed by
              designing a PCB for the same project).
             #+END_DIV
       #+attr_html: :class about-indented
       #+BEGIN_DIV       
      (Note: execution of code with *kati* is still buggy.
	     In some cases it doesn't work at all, in other cases *kati*
             just takes forever to finish execution. Occasionally this is
             caused by a cat sitting on the keyboard.)
       #+END_DIV
*BUGS*
       #+attr_html: :class about-indented
       #+BEGIN_DIV       
       plenty. some are even documented.
       #+END_DIV
*AUTHORS*
       #+attr_html: :class about-indented
       #+BEGIN_DIV       
       kati's parents.
       #+END_DIV
*COPYRIGHT*
       #+attr_html: :class about-indented
       #+BEGIN_DIV       
       changes and redistribution of *kati* are prohibited by law.
       #+END_DIV


#+begin_export html
<div class="about">
   <div class="about-column">KATI(6)</div>
   <div class="about-column">Games Manual</div>
   <div class="about-column">KATI(6)</div>
</div>
#+end_export
