#+TITLE: stuff

#+ATTR_HTML: :class archive
#+BEGIN_DIV
@@html:<li>@@ @@html:<span class="archive-item"><span class="archive-date">@@ [18.11.2020, 20:00 CET] @@html:</span>@@ [[file:posts/PinkPad/index.org][The PinkPad v1 2020 Lockdown Edition]]@@html:<div class="description">@@ I was always jealous about those hot little mini-laptops. So I built my own one with a Raspberry Pi and a toy laptop. @@html:</div>@@ @@html:<div class="keywords">@@ raspberry pi, linux, arch linux, coding @@html:</div>@@ @@html:</span>@@ @@html:</li>@@
@@html:<li>@@ @@html:<span class="archive-item"><span class="archive-date">@@ [21.12.2019, 20:00 CET] @@html:</span>@@ [[file:posts/emacs_themes/index.org][Emacs Themes]]@@html:<div class="description">@@ It's important to feel at home in your beloved editor, so this post is about creating custom themes in Emacs. @@html:</div>@@ @@html:<div class="keywords">@@ emacs, beginner-friendly, themes @@html:</div>@@ @@html:</span>@@ @@html:</li>@@
@@html:<li>@@ @@html:<span class="archive-item"><span class="archive-date">@@ [18.11.2020, 20:00 CET] @@html:</span>@@ [[file:posts/changes_in_blogging_setup/index.org][Changes in Blogging Setup]]@@html:<div class="description">@@ A few things bothered me in my blogging setup, here's what I changed @@html:</div>@@ @@html:<div class="keywords">@@ emacs, org-mode, blogging, code @@html:</div>@@ @@html:</span>@@ @@html:</li>@@
@@html:<li>@@ @@html:<span class="archive-item"><span class="archive-date">@@ [27.11.2019, 20:00 CET] @@html:</span>@@ [[file:posts/first_post/index.org][Bitshiftcrazy]]@@html:<div class="description">@@ So this is my very first attempt to write a blog. Ever. Find out why and what and how in this post. @@html:</div>@@ @@html:<div class="keywords">@@ blog, org-mode, programming, instagram @@html:</div>@@ @@html:</span>@@ @@html:</li>@@
#+END_DIV
