#+TITLE: stuff

#+ATTR_HTML: :class archive
#+BEGIN_DIV
@@html:<li>@@ @@html:<span class="archive-item"><span class="archive-date">@@ [07.10.2026, 20:00 CEST] @@html:</span>@@ [[file:posts/spell_tome/index.org][Printed Circuit Sorcery: The RP2040 Spell Tome]]@@html:<div class="description">@@ I built an RP2040-based handheld devboard that looks as if a Game Boy Classic and a spell tome had a baby. It's made from two sandwiched PCBs and was meant as a repurposable Christmas gift for my DnD group. And yes, it runs DOOM as well. Just because, but also to prove said repurposability. @@html:</div>@@ @@html:<div class="keywords">@@ raspberry pi, rp2040, seeed xiao rp2040, dnd, tabletop @@html:</div>@@ @@html:</span>@@ @@html:</li>@@
@@html:<li>@@ @@html:<span class="archive-item"><span class="archive-date">@@ [27.09.2026, 20:00 CEST] @@html:</span>@@ [[file:posts/clotty_intro/index.org][My Uterus runs DOOM: Introducing Clotty v1.1]]@@html:<div class="description">@@ My uterus runs DOOM. Figuratively, approximately every four weeks. So I built Clotty, a uterus-shaped RP2040 hybrid of sensor board and gaming device that's supposed to help me keep track of (and gamify) this recurrent, unpleasant experience (i.e. my period, if that wasn't clear). And of course it runs DOOM literally now as well. Because ever since I was a little girl, I dreamt of being the first woman to play DOOM on a uterus. @@html:</div>@@ @@html:<div class="keywords">@@ raspberry pi, rp2040, sensors, doom, period @@html:</div>@@ @@html:</span>@@ @@html:</li>@@
@@html:<li>@@ @@html:<span class="archive-item"><span class="archive-date">@@ [25.05.2026, 20:00 CEST] @@html:</span>@@ [[file:posts/PinkPadPaw/index.org][The PinkPad's Paw Mouse Explained]]@@html:<div class="description">@@ Rumour has been spreading online that the PinkPad's paw mouse isn't working. Since I started that rumour, let me debunk it (and suck at Doom in the process). @@html:</div>@@ @@html:<div class="keywords">@@ raspberry pi, linux, arch linux, coding, cyberdeck, hid, doom @@html:</div>@@ @@html:</span>@@ @@html:</li>@@
@@html:<li>@@ @@html:<span class="archive-item"><span class="archive-date">@@ [01.03.2026, 11:00 CET] @@html:</span>@@ [[file:posts/d20_pcb/index.org][Building a Slightly Sentient d20 PCB]]@@html:<div class="description">@@ I built a mildly sentient d20 PCB, for dice rolls and attitude @@html:</div>@@ @@html:<div class="keywords">@@ pcb, dnd, microcontroller, charlieplexing, attiny84 @@html:</div>@@ @@html:</span>@@ @@html:</li>@@
@@html:<li>@@ @@html:<span class="archive-item"><span class="archive-date">@@ [22.10.2021, 10:00 CEST] @@html:</span>@@ [[file:posts/favorite_books/index.org][My Favorite Programming Books - Pt 1]]@@html:<div class="description">@@ On popular demand (aka 5 people asked for it) here's a list of my favorite programming books. This is part one. @@html:</div>@@ @@html:<div class="keywords">@@ books, programming, Software Development @@html:</div>@@ @@html:</span>@@ @@html:</li>@@
@@html:<li>@@ @@html:<span class="archive-item"><span class="archive-date">@@ [21.03.2021, 12:00 CET] @@html:</span>@@ [[file:posts/fuzix_on_pico/index.org][FUZIX on the Raspberry Pi Pico: Installing from Arch Linux]]@@html:<div class="description">@@ The Raspberry Pi Foundation recently released their first microntroller, the Pico. And while the Pico can't run Linux unfortunately, it can give you the pleasure of playing with an old-school UNIX-like system: FUZIX. @@html:</div>@@ @@html:<div class="keywords">@@ Raspberry Pi, Raspberry Pi Pico, Arch Linux, FUZIX, UNIX @@html:</div>@@ @@html:</span>@@ @@html:</li>@@
@@html:<li>@@ @@html:<span class="archive-item"><span class="archive-date">@@ [20.12.2020, 20:00 CET] @@html:</span>@@ [[file:posts/linux_cookies/index.org][Linux Cookies]]@@html:<div class="description">@@ I made 3D-printable models for Linux Cookie Cutters of 5 popular distros. Here are the (not entirely serious) installation instructions for the various distros as well as the cookie source code. @@html:</div>@@ @@html:<div class="keywords">@@ linux, cookies, linux cookies, c programming, programming, ubuntu, debian, kali, arch, arch linux, gentoo, 3D printing @@html:</div>@@ @@html:</span>@@ @@html:</li>@@
@@html:<li>@@ @@html:<span class="archive-item"><span class="archive-date">@@ [18.11.2020, 20:00 CET] @@html:</span>@@ [[file:posts/changes_in_blogging_setup/index.org][Changes in Blogging Setup]]@@html:<div class="description">@@ A few things bothered me in my blogging setup, here's what I changed @@html:</div>@@ @@html:<div class="keywords">@@ emacs, org-mode, blogging, code @@html:</div>@@ @@html:</span>@@ @@html:</li>@@
@@html:<li>@@ @@html:<span class="archive-item"><span class="archive-date">@@ [18.11.2020, 20:00 CET] @@html:</span>@@ [[file:posts/PinkPad/index.org][The PinkPad v1 2020 Lockdown Edition]]@@html:<div class="description">@@ I was always jealous about those hot little mini-laptops. So I built my own one with a Raspberry Pi and a toy laptop. @@html:</div>@@ @@html:<div class="keywords">@@ raspberry pi, linux, arch linux, coding @@html:</div>@@ @@html:</span>@@ @@html:</li>@@
@@html:<li>@@ @@html:<span class="archive-item"><span class="archive-date">@@ [21.12.2019, 20:00 CET] @@html:</span>@@ [[file:posts/emacs_themes/index.org][Emacs Themes]]@@html:<div class="description">@@ It's important to feel at home in your beloved editor, so this post is about creating custom themes in Emacs. @@html:</div>@@ @@html:<div class="keywords">@@ emacs, beginner-friendly, themes @@html:</div>@@ @@html:</span>@@ @@html:</li>@@
@@html:<li>@@ @@html:<span class="archive-item"><span class="archive-date">@@ [27.11.2019, 20:00 CET] @@html:</span>@@ [[file:posts/first_post/index.org][Bitshiftcrazy]]@@html:<div class="description">@@ So this is my very first attempt to write a blog. Ever. Find out why and what and how in this post. @@html:</div>@@ @@html:<div class="keywords">@@ blog, org-mode, programming, instagram @@html:</div>@@ @@html:</span>@@ @@html:</li>@@
#+END_DIV
