#+title: Disclaimer 

*  
** 
*** Disclaimer  

This disclaimer ("Disclaimer", "Agreement") is an agreement between bitshiftcrazy ("Website Operator", "us", "we" or "our") 
and you ("User", "you" or "your"). This Disclaimer sets forth the general guidelines, 
terms and conditions of your use of the bitshiftcrazy.com website and any of its products or services (collectively, "Website" or "Services"). 
    
*** Representation

Any views or opinions represented in this Website are personal and belong solely to bitshiftcrazy and do not represent 
those of people, institutions or organizations that the owner may or may not be associated with in professional or personal 
capacity unless explicitly stated. Any views or opinions are not intended to malign any religion, ethnic group, club, organization, company, or individual.

*** Content and postings

You may print a copy of any part of this Website for your personal or non-commercial use. 

*** Indemnification and warranties

While we have made every attempt to ensure that the information contained on the Website is correct, bitshiftcrazy is not responsible for any errors or omissions,
 or for the results obtained from the use of this information. All information on the Website is provided "as is", with no guarantee of completeness, accuracy, 
timeliness or of the results obtained from the use of this information, and without warranty of any kind, express or implied. 
In no event will bitshiftcrazy be liable to you or anyone else for any decision made or action taken in reliance on the information on the Website or 
for any consequential, special or similar damages, even if advised of the possibility of such damages. Information on the Website is for general information 
purposes only and is not intended to provide legal, financial, medical, or any other type of professional advice. Please seek professional assistance should you 
require it. Furthermore, information contained on the Website and any pages linked to and from it are subject to change at any time and without warning.

We reserve the right to modify this Disclaimer relating to the Website or Services at any time, effective upon posting of an updated version 
of this Disclaimer on the Website. Continued use of the Website after 
any such changes shall constitute your consent to such changes.

*** Acceptance of this disclaimer

You acknowledge that you have read this Disclaimer and agree to all its terms and conditions. 
By accessing the Website you agree to be bound by this Disclaimer. If you do not agree to abide by the terms of this Disclaimer, 
you are not authorized to use or access the Website. 

Policy was created with https://www.WebsitePolicies.com

This document was last updated on December 21, 2019
